### ISSUE TITLE
Implement higher-level mappings

### ISSUE THREAD

**Issue by Kernald** [JadKHaddad/tm1637#3]
Thanks for this library! I very much appreciate having a crate using `embedded-hal` for this.

Do you have thoughts about implementing higher-level mappings than e.g. the current `DigitBits::from_digits` - maybe something to convert arbitrary numbers to bytes? We know that we only have 4 digits to work with, so we could offer some nice interfaces here.

**Comment by JadKHaddad** [comment]
@Kernald Thank you for your suggestion.

This functionality was intentionally not implemented due to several reasons:
- Function Signature:
    - ``fn from_number(number: u16) -> [u8; 4]``: Do we want to force users to always allocate 4 bytes of memory?
    - ``fn from_number(number: u16, buf: &mut [u8])``: Or do we want users to provide their allocated slice?
- Function Behavior:
    - How should the function behave when the number is too big? Should it return an error or ignore the overflow?
    - How should the function behave when the number of digits is too small? Should it order digits from left to right or from right to left?
- Negative Numbers: The minus sign is also supported by the display.
- Other Functionalities: Implementing this function could lead to additional features, like ``UpCharBits::from(s: &str)`` or converting any sequence of ASCII bytes into the corresponding display bytes.

I've checked how other libraries implement such functionality, but as a user, I find it often makes things more complicated due to all the limitations and edge cases. As a result, I end up adapting my code to work with the library's constraints. For these reasons, I believe it's better for users to implement the logic they are comfortable with.

**Comment by Kernald** [comment]
Cheers - that makes sense! Thanks for the detailed reply.
